### ISSUE TITLE
Uploading QR code via Camera option on iOS crashes the app

### ISSUE THREAD

**Issue by mobitar** [standardnotes/token-vault#15]
This one sounds like it would be difficult to debug, but just posting it here for reference

**Comment by mrtpcet** [comment]
I still have this problem...

**Comment by fegyi001** [comment]
I also have this problem.

**Comment by OddHouseGames** [comment]
Still having this issue.

**Comment by JaspalSuri** [comment]
Sorry to hear that. 😞 We still plan to address this issue and I will comment on this thread when an updated version of the TokenVault extension is ready to test. 🙂
