### ISSUE TITLE
Provide a way to arrange/drag the entries

### ISSUE THREAD

**Issue by x80486** [standardnotes/token-vault#19]
This comes pretty handy since TokenVault entries are arranged in the way they are entered and there is no current way to sort them.

Something like this:

![image](https://user-images.githubusercontent.com/34633617/71789278-075aaf80-2ff8-11ea-92a4-80f67f98e30c.png)

> The _hamburguer_ icon serves that purpose (to drag/reorder the entries) in that case.

**Comment by h0jeZvgoxFepBQ2C** [comment]
You can change the fault editor to text and change the order of the entries, then switch back to the vault editor and the order is like you wish.

**Comment by AaronW0820** [comment]
Thanks for the workaround mentioned above. Would still be a great addition to be able to sort them alphabetically!

**Comment by JaspalSuri** [comment]
I've added it to the same report for this enhancement request. Thanks for the feedback!

**Comment by saizai** [comment]
Second this. I suggest a couple tweaks vs @x80486's mockup (partially based on Google Authenticator):
1. burger grab handle on left side, full height
2. on mobile, maybe only show grab handle after long press, to avoid accidental move when intending to swipe scroll
3. add auto sort to editor options, to alpha-with-logical-numbers (1,2,10,12 not 1,10,12,2) sort all entries immediately & when being added, by the tuple (service, account, notes)
