### ISSUE TITLE
Please add a HEX-BackgroundColor option for the TokenVault entries

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [standardnotes/token-vault#26]
It would be great if you could add a background-color option (hex code) for the TokenVault-Entries, since I have a lot of entries which I use. Specifying a background color would help me a lot to find the corresponding entry much faster?

I also don't think that this would be hard to implement?

**Comment by JaspalSuri** [comment]
Thanks for the feedback! I'll pass it along for review!

**Comment by mobitar** [comment]
What about a search/filter box? Colors would look good in one theme but not in another.

**Comment by TheodoreChu** [comment]
Background colors per-entry are probably not too difficult to implement. One way to do it would be by adding inline styling to [AuthEntry.js](https://github.com/sn-extensions/token-vault/blob/master/app/components/AuthEntry.js)

**Comment by h0jeZvgoxFepBQ2C** [comment]
A search filter is nice, but no replacement for the colors, since you have to reach the keyboard instead of just scrolling, which is not as comfortable as just mouse scrolling.

About the themes: I don't think this is a big issue, since you can choose the colors by yourself.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is there any feedback to this? Would you accept a PR (not sure if I'm experienced enough to do so)?

**Comment by JaspalSuri** [comment]
I will pass this along to the dev team and someone will get back to you sometime next week (if not sooner). :)

**Comment by mobitar** [comment]
We're not currently undertaking new features on editors until we complete our client applications major 3.5 release.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is there any estimate when 3.5 will arrive?

**Comment by JaspalSuri** [comment]
Currently no ETA on when it will arrive, but you can track some of the [dev team's progress here](https://github.com/standardnotes/snjs/commits/004).

**Comment by h0jeZvgoxFepBQ2C** [comment]
So are there any plans for this feature now, since 3.5 is out?

Btw: I helped myself (a bit) by just adding emojis to the tokens which I want to hover 🌊🌊🌊🛳🌊🌊🏖🌴..
But setting a background color would help much more to find the entries fast.

**Comment by JaspalSuri** [comment]
>Btw: I helped myself (a bit) by just adding emojis to the tokens which I want to hover 🌊🌊🌊🛳🌊🌊🏖🌴..

That's great to hear!

>So are there any plans for this feature now, since 3.5 is out?

I've added it to our todo list, so it's just a matter of time until we get to revisiting the tasks pertaining to the TokenVault editor. The resulting changes might not be similar what you initially had in mind, but we'll consider what will ultimately be the best way to make each entry distinguishable (while keeping the editor maintainable).

**Comment by h0jeZvgoxFepBQ2C** [comment]
Since https://github.com/standardnotes/token-vault/pull/49 is merged, I'm closing this issue. Thank you so much!
