### ISSUE TITLE
Cannot see copy prompt in long token list

### ISSUE THREAD

**Issue by ZettaCore** [standardnotes/token-vault#41]
When I am in the token vault and trying to copy a token, the prompt saying that the token has been copied shows near the top of the list. This is fine if I am copying a token from the top of the list because I can see it and I know it's been copied to my clipboard but if I scroll down to copy a token from the bottom of the list, I don't know if the token has been copied or not because the copy prompt won't move to the bottom.

**Comment by JaspalSuri** [comment]
Hi @ZettaCore,

Sorry for the delayed response. I was able to reproduce this issue and will forward it to our extensions dev for further review. Thanks for taking the time to report this!
